'''Instructions
You are given two strings s and t.

String t is generated by random shuffling string s and then add one more letter at a random position.

Return the letter that was added to t.
'''
'''Examples
Input: s = "abcd", t = "abcde"
Output: "e"
Explanation: 'e' is the letter that was added.

Input: s = "", t = "y"
Output: "y"
'''
'''Thoughts
1. Get a dictionary of string s characters and its count
2. Loop through t and check if it is in the dictionary's key
3. If it isn't or dictionary at the value is 0, return the value
3. If it is, dictionary at the value minus 1
'''

def find_difference(s:str, t):
    d = {ch: s.count(ch) for ch in set(s)}
    for character in t:
        if character not in d.keys():
            return character
        else:
            if d[character] == 0:
                return character
            else:
                d[character] -= 1
    return ''